import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Provider } from "@/components/Provider";
import { Authenticated, useConvexAuth, useQuery } from "convex/react";
import { UserNavBar } from "@/components/UserNavBar";
import { Avatar, AvatarImage, AvatarFallback } from "@radix-ui/react-avatar";
import { PersonStandingIcon } from "lucide-react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { api } from "../../convex/_generated/api";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased w-full h-full", fontSans.variable)}>
        <Provider>
          <main className="p-8 w-full h-full">
          <UserNavBar /> 
          {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
